# Manual mapping of stations for missing NaPTAN data
# National Rail Stations
9100WORCPHL = "9100WORCPWY" # Worcester Parkway
9100CNNBELL = "9100CNNB" # Cannonbury
9100HIGHBYE = "9100HIGHBYA" # Highbury & Islington
# Light Rail Stations
9400ZZDLCUS2 = "9400ZZDLCUS1" # Custom House (DLR)
9400ZZDLPRE2 = "9400ZZDLPRE1" # Prince Regent (DLR)
9400ZZDLKGV2 = "9400ZZDLKGV1" # King George V (DLR)
9400ZZDLSHA2 = "9400ZZDLSHA1" # Shadwell (DLR)
9400ZZDLBNK2 = "9400ZZDLBNK1" # Bank (DLR)
9400ZZDLTWG2 = "9400ZZDLTWG1" # Tower Gateway (DLR)
9400ZZDLLCA2 = "9400ZZDLLCA1" # London City Airport (DLR)
9400ZZDLISL2 = "9400ZZDLISL1" # Island Gardens (DLR)
9400ZZDLCUT2 = "9400ZZDLCUT1" # Cutty Sark (DLR)
# Tube Stations
9400ZZLUSKT2 = "9400ZZLUSKT1" # South Kenton (Underground)
9400ZZLUKPK2 = "9400ZZLUKPK1" # Kilburn Park (Underground)
9400ZZLUMVL2 = "9400ZZLUMVL1" # Maida Vale (Underground)
9400ZZLUWKA2 = "9400ZZLUWKA1" # Warwick Avenue (Underground)
9400ZZLULBN2 = "9400ZZLULBN1" # Labeth North (Underground)
9400ZZLUBLG2 = "9400ZZLUBLG1" # Bethnal Green (Underground)
9400ZZLUBND4 = "9400ZZLUBND3" # Bond Street (Underground)
9400ZZLUMBA2 = "9400ZZLUMBA1" # Marble Arch (Underground)
9400ZZLULGT2 = "9400ZZLULGT1" # Lancaster Gate (Underground)
9400ZZLUQWY2 = "9400ZZLUQWY1" # Queensway (Underground)
9400ZZLUSBC2 = "9400ZZLUSBC1" # Shepard's Bush (Underground)
9400ZZLUHGR2 = "9400ZZLUHGR1" # Hangar Lane (Underground)
9400ZZLUPVL2 = "9400ZZLUPVL1" # Perivale (Underground)
9400ZZLUNHT2 = "9400ZZLUNHT1" # Northolt (Underground)
9400ZZLUSRP2 = "9400ZZLUSRP1" # South Ruislip (Underground)
9400ZZLURSG2 = "9400ZZLURSG1" # Ruislip Gardens (Underground)
9400ZZLUGTH2 = "9400ZZLUGTH1" # Gants Hill (Underground)
9400ZZLURBG2 = "9400ZZLURBG1" # Redbridge (Underground)
9400ZZLUWSD2 = "9400ZZLUWSD1" # Wanstead (Underground)
9400ZZLUKSX8 = "9400ZZLUKSX7" # King's Cross St. Pancras (Underground)
9400ZZLURYO2 = "9400ZZLURYO1" # Royal Oak (Underground)
9400ZZLUWIP2 = "9400ZZLUWIP1" # Wimbledon Park (Underground)
9400ZZLUUPB2 = "9400ZZLUUPB1" # Upminster Bridge (Underground)
9400ZZLUEPK2 = "9400ZZLUEPK1" # Elm Park (Underground)
9400ZZLUUPY2 = "9400ZZLUUPY1" # Upney (Underground)
9400ZZLUGBY2 = "9400ZZLUGBY1" # Gunnersbury (Underground)
9400ZZLUSFS2 = "9400ZZLUSFS1" # Southfields (Underground)
9400ZZLUNDN2 = "9400ZZLUNDN1" # Neasdon (Underground)
9400ZZLUDOH2 = "9400ZZLUDOH1" # Dollis Hill (Underground)
9400ZZLUWIG2 = "9400ZZLUWIG1" # Willsden Green (Underground)
9400ZZLUSWC2 = "9400ZZLUSWC1" # Swiss Cottage (Underground)
9400ZZLUSJW2 = "9400ZZLUSJW1" # St. John's Wood (Underground)
9400ZZLUCYF2 = "9400ZZLUCYF1" # Canary Wharf (Underground)
9400ZZLULNB3 = "9400ZZLULNB2" # London Bridge(Underground)
9400ZZLUWLO8 = "9400ZZLUWLO6" # Waterloo (Underground)
9400ZZLUWHP2 = "9400ZZLUWHP1" # West Hampstead (Underground)
9400ZZLUNKP2 = "9400ZZLUNKP1" # Northwick Park (Underground)
9400ZZLUPRD2 = "9400ZZLUPRD1" # Preston Road (Underground)
9400ZZLUHGT2 = "9400ZZLUHGT1" # Highgate (Underground)
9400ZZLUACY2 = "9400ZZLUACY1" # Archway (Underground)
9400ZZLUAGL2 = "9400ZZLUAGL1" # Angel (Underground)
9400ZZLUODS2 = "9400ZZLUODS1" # Old Street (Underground)
9400ZZLULNB4 = "9400ZZLULNB2" # London Bridge (Underground)
9400ZZLUCPN2 = "9400ZZLUCPN1" # Clapham North (Underground)
9400ZZLUCPC2 = "9400ZZLUCPC1" # Clapham Common (Underground)
9400ZZLUCPS2 = "9400ZZLUCPS1" # Clapham South (Underground)
9400ZZLUBLM2 = "9400ZZLUBLM1" # Balham (Underground)
9400ZZLUTBC2 = "9400ZZLUTBC1" # Tooting Bec (Underground)
9400ZZLUTBY2 = "9400ZZLUTBY1" # Tooting Broadway (Underground)
9400ZZLUCSD2 = "9400ZZLUCSD1" # Colliers Wood (Underground)
9400ZZLUSWN2 = "9400ZZLUSWN1" # South Wimbledon (Underground)
9400ZZLUMTC2 = "9400ZZLUMTC1" # Mornington Crescent (Underground)
9400ZZLUGDG2 = "9400ZZLUGDG1" # Goodge Street (Underground)
9400ZZLUWLO7 = "9400ZZLUWLO6" # Waterloo (Underground)
9400ZZLUBTK2 = "9400ZZLUBTK1" # Burnt Oak (Underground)
9400ZZLUCND2 = "9400ZZLUCND1" # Colindale (Underground)
9400ZZLUHCL2 = "9400ZZLUHCL1" # Hendon Central (Underground)
9400ZZLUBTX2 = "9400ZZLUBTX1" # Brent Cross (Underground)
9400ZZLUCFM2 = "9400ZZLUCFM1" # Chalk Farm (Underground)
9400ZZLUHPC2 = "9400ZZLUHPC1" # Hyde Park Corner (Underground)
9400ZZLUCAR2 = "9400ZZLUCAR1" # Caledonian Road (Underground)
9400ZZLUOAK2 = "9400ZZLUOAK1" # Oakwood (Underground)
9400ZZLUSGT2 = "9400ZZLUSGT1" # Southgate (Underground)
9400ZZLUBDS2 = "9400ZZLUBDS1" # Bounds Green (Underground)
9400ZZLUWOG2 = "9400ZZLUWOG1" # Wood Green (Underground)
9400ZZLUTPN2 = "9400ZZLUTPN1" # Turnpike Lane (Underground)
9400ZZLUMRH2 = "9400ZZLUMRH1" # Manor House (Underground)
9400ZZLUHWY2 = "9400ZZLUHWY1" # Holloway Road (Underground)
9400ZZLUGPK6 = "9400ZZLUGPK5" # Green Park (Underground)
9400ZZLUHWC2 = "9400ZZLUHWC1" # Hounslow Central (Underground)
9400ZZLUHWT2 = "9400ZZLUHWT1" # Hounslow West (Underground)
9400ZZLUHNX2 = "9400ZZLUHNX1" # Hatton Cross (Underground)
9400ZZLUBLR2 = "9400ZZLUBLR1" # Blackhorse Road (Underground)
9400ZZLUTMH2 = "9400ZZLUTMH1" # Tottenham Hale (Underground)
9400ZZLUPCO2 = "9400ZZLUPCO1" # Pimlico (Underground)
9400ZZLUVXL2 = "9400ZZLUVXL1" # Vauxhall (Underground)
# Coach Stops
490000104W = "490000104E" # Heathrow Terminal 4
# Bus Stops
2900BMNDRSR = "2900Y035" # Sandown Road -> Midland Close
2900BMNDRKR = "2900Y036" # Sandown Road -> Midland Close
3900BMRRS = "3900BMKRCWS" # Car Wash (Also manually added)
450018084 = "450018085" # Illingworth Ogden View Close
450018087 = "450018086" # Illingworth Heathmoor Close
450018089 = "450018088" # Illingworth Heathmoor Mount